# Build_toolchain打包到toolchain_out.tar.gz 

name: Padavan-ng_Build_toolchain
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
  ANY_SSH: false
  RUN_TEST: false

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 
    
    steps:
    - name: Checkout Master              # 导入主分支
      uses: actions/checkout@master
    - name: Initialization Environment   # 初始环境的设置
      env:
        DEBIAN_FRONTEND: noninteractive  # 非交互模式
      run: |
        if [ $ANY_SSH != true ] ; then
           # 安装依赖包
           sudo apt-get update
           sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
           cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
           pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
           sudo timedatectl set-timezone 'Asia/Shanghai'  # 设置时区
        fi
       
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}   
    
    - name: Clone Source Code
      run: |             
        if [ $ANY_SSH != true ] ; then
           # 克隆源码
           git clone --depth=1 https://github.com/hminid/padavan-ng.git /opt/rt-n56u
        fi

    - name: Build ToolChain
      run: |
       if [ $ANY_SSH != true ] ; then
          # 构建工具链
          cd /opt/rt-n56u/toolchain
          sudo ./clean_sources.sh
          sudo ./build_toolchain.sh
        fi

    - name: Copy toolchain File
      run: |
        if [ $ANY_SSH != true ] ; then
          #打包tar.gz
          cd /opt/rt-n56u/toolchain/out/
          tar -zcvf /opt/rt-n56u/toolchain/toolchain_out.tar.gz *
        fi
     
    - name: TEST
      run: |
        if [ $RUN_TEST = true ] ; then
        #####################################################################
        mkdir -p /opt/rt-n56u/toolchain/out/
        echo hello > /opt/rt-n56u/toolchain/out/world.txt
        #打包tar.gz
        cd /opt/rt-n56u/toolchain/out/
        tar -zcvf /opt/rt-n56u/toolchain/toolchain_out.tar.gz *
        #####################################################################
        fi
    
    - name : Upload packages tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: toolchain_out.tar.gz
        path: /opt/rt-n56u/toolchain/toolchain_out.tar.gz 
